#!/bin/sh
aws cloudformation create-stack \
  --stack-name static-site-deploy \
  --template-body file://deployment-resources.template \
  --capabilities CAPABILITY_IAM \
  --parameters ParameterKey=pDeploymentBucket,ParameterValue=static-site-deploy ParameterKey=pDestinationBucket,ParameterValue=www.lerch.org
