#!/bin/sh
BUCKET_NAME=static-site-deploy
ZIP_FILE=deployment.zip

# Create source package - everything under src/
pushd src >/dev/null && \
zip -r $ZIP_FILE * -x "*node_modules*" -x "*test*" >/dev/null && \
zip -r $ZIP_FILE                \
 node_modules/follow-redirects  \
 node_modules/recursive-readdir \
 node_modules/async             \
 > /dev/null && \
aws s3 mv $ZIP_FILE s3://$BUCKET_NAME/
popd >/dev/null
